In [187]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, auc, roc_auc_score

In [1]:
os.chdir(r"C:\Users\Dell\Desktop\Finalproject")

NameError: name 'os' is not defined

In [189]:
df2 = pd.read_csv("df_val_clean.csv")

In [190]:
train = pd.read_csv("train_loan.csv")
test = pd.read_csv("test_loan.csv")

In [191]:
#splitting
y_train = train['default_ind']
y_train = y_train.as_matrix()
y_test = test['default_ind']
y_test = y_test.as_matrix()
X_train = train.drop('default_ind', axis = 1)  
X_train = X_train.as_matrix()
X_test = test.drop('default_ind', axis = 1)
X_test = X_test.as_matrix()

In [192]:
# normalizing data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)

In [193]:
scaler=StandardScaler()
scaler.fit(X_test)
X_test=scaler.transform(X_test)

In [194]:
y_train = y_train.astype(int)
y_test = y_test.astype(int)

In [195]:
df2=df2.drop(["default_ind"],axis=1)

In [196]:
df3 = df2.as_matrix()

In [197]:
#validation

In [198]:
#using xgboost
import xgboost

In [199]:
from xgboost import XGBRegressor
my_model = XGBRegressor(learning_rate =0.09,subsample=0.5,colsample_bytree=0.85,reg_alpha=0.005,min_child_weight = 5)

In [200]:
my_model.fit(X_train, y_train, verbose=False)

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.85,
       gamma=0, learning_rate=0.09, max_delta_step=0, max_depth=3,
       min_child_weight=5, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0.005, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=0.5)

In [201]:
test_y_pred = my_model.predict(df3)

In [202]:
df5= pd.DataFrame(test_y_pred, columns= ['loan_status'])

In [203]:
y_pred_class=[]
for value in df5.loan_status:
    if value > 0.5:
        y_pred_class.append(1)
    else:
        y_pred_class.append(0)

In [204]:
df86 = pd.DataFrame(y_pred_class,columns= ['loan_status'])

In [205]:
df_c = pd.concat([df2, df86], axis=1)
df_c

,loan_amnt,term,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,open_acc,pub_rec,revol_util,tot_cur_bal,total_rev_hi_lim,loan_status
0,3000.0,1,2,1,5,80000.0,1,9,17.94,0.0,15.0,0.0,53.9,140220.450507,32939.158698,0
1,7000.0,1,3,8,5,47004.0,0,2,23.51,0.0,7.0,0.0,85.6,140220.450507,32939.158698,0
2,10000.0,1,3,2,5,29120.0,2,2,22.83,0.0,11.0,0.0,63.6,140220.450507,32939.158698,0
3,12500.0,1,2,1,5,27000.0,2,2,16.04,0.0,6.0,0.0,50.0,140220.450507,32939.158698,0
4,17500.0,1,4,6,5,40000.0,2,11,19.47,0.0,5.0,0.0,58.9,140220.450507,32939.158698,0
5,14000.0,1,4,4,5,28000.0,2,9,6.34,0.0,5.0,0.0,79.4,140220.450507,32939.158698,0
6,15300.0,1,6,6,5,85000.0,2,1,20.58,0.0,14.0,0.0,89.7,140220.450507,32939.158698,0
7,6000.0,1,2,0,5,81000.0,1,6,13.66,1.0,6.0,0.0,50.0,140220.450507,32939.158698,0
8,16000.0,1,4,7,5,65000.0,0,2,15.56,0.0,8.0,0.0,87.1,140220.450507,32939.158698,0
9,16000.0,1,2,10,4,40000.0,2,2,9.39,0.0,6.0,0.0,28.5,140220.450507,32939.158698,0
10,11000.0,1,3,10,1,129000.0,2,2,10.94,0.0,10.0,0.0,24.1,140220.450507,32939.158698,0
11,22475.0,1,3,7,1,52000.0,2,2,15.23,0.0,7.0,0.0,61.8,140220.450507,32939.158698,0
12,8400.0,1,4,5,5,87996.0,0,6,11.35,0.0,8.0,0.0,80.3,140220.450507,32939.158698,0
13,21000.0,1,4,10,1,109000.0,2,2,7.75,0.0,9.0,0.0,50.3,140220.450507,32939.158698,0
14,16000.0,1,4,2,5,50000.0,1,2,11.04,0.0,10.0,0.0,42.2,140220.450507,32939.158698,0
15,15600.0,1,2,10,5,50000.0,1,12,5.78,0.0,8.0,0.0,35.7,140220.450507,32939.158698,0
16,18825.0,1,4,4,1,44000.0,2,2,24.98,0.0,9.0,0.0,93.2,140220.450507,32939.158698,0
17,12300.0,1,3,2,1,30000.0,1,2,12.76,0.0,8.0,0.0,55.5,140220.450507,32939.158698,0
18,18000.0,1,3,1,1,84000.0,2,1,11.41,0.0,11.0,0.0,83.2,140220.450507,32939.158698,0
19,18000.0,1,4,1,1,62000.0,2,2,7.82,0.0,8.0,0.0,86.7,140220.450507,32939.158698,0
20,20000.0,1,3,2,1,56000.0,2,1,12.15,0.0,9.0,0.0,59.9,140220.450507,32939.158698,0
21,25000.0,1,5,10,5,75000.0,2,2,19.63,0.0,9.0,0.0,91.5,140220.450507,32939.158698,0
22,18000.0,1,5,3,5,90000.0,1,1,11.32,0.0,10.0,0.0,85.2,140220.450507,32939.158698,0
23,20000.0,1,2,2,1,175000.0,2,2,5.23,0.0,12.0,0.0,34.1,140220.450507,32939.158698,0
24,20000.0,1,4,7,5,50000.0,2,1,22.82,0.0,12.0,0.0,56.7,140220.450507,32939.158698,0
25,20000.0,1,2,7,4,85000.0,1,4,10.21,0.0,13.0,0.0,54.8,140220.450507,32939.158698,0
26,16000.0,1,5,8,1,54000.0,1,4,16.89,0.0,9.0,0.0,56.2,140220.450507,32939.158698,0
27,3000.0,1,5,3,5,53004.0,1,9,10.73,1.0,3.0,0.0,79.4,140220.450507,32939.158698,0
28,17000.0,1,3,8,5,65000.0,0,2,16.84,0.0,11.0,0.0,62.7,140220.450507,32939.158698,0
29,25000.0,1,5,3,1,85000.0,2,1,17.15,1.0,7.0,0.0,87.9,140220.450507,32939.158698,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602909,20000.0,0,2,10,1,78000.0,1,2,20.51,0.0,16.0,0.0,46.1,256735.000000,72400.000000,0
602910,16000.0,0,1,9,1,200000.0,1,2,26.82,0.0,29.0,0.0,62.5,349131.000000,47300.000000,0
602911,5000.0,0,3,10,5,55000.0,2,9,11.30,0.0,2.0,0.0,38.2,31933.000000,1300.000000,0
602912,21000.0,1,3,10,5,82000.0,1,2,20.23,2.0,15.0,0.0,87.6,72123.000000,37400.000000,0
602913,13000.0,0,1,10,1,85000.0,0,1,8.05,1.0,8.0,0.0,92.3,199384.000000,7200.000000,0
602914,20000.0,0,1,2,1,72000.0,1,2,27.24,0.0,15.0,0.0,53.1,388140.000000,39700.000000,0
602915,10300.0,1,3,10,5,93600.0,1,2,15.72,1.0,13.0,0.0,46.6,41956.000000,22000.000000,0
602916,15000.0,0,2,0,5,70000.0,2,2,8.47,0.0,8.0,0.0,98.0,15724.000000,9700.000000,0
602917,15000.0,1,2,4,5,57000.0,1,2,15.77,0.0,8.0,0.0,56.9,33529.000000,26100.000000,0
602918,6000.0,0,4,10,1,90000.0,2,2,2.84,0.0,9.0,0.0,78.9,384500.000000,8500.000000,0
602919,26950.0,0,1,0,5,54000.0,2,2,18.11,0.0,14.0,0.0,24.9,41650.000000,129100.000000,0
602920,23000.0,1,4,10,1,50000.0,1,1,31.95,0.0,13.0,0.0,63.3,48978.000000,65600.000000,0
602921,18700.0,1,4,10,5,52000.0,1,2,11.28,0.0,8.0,0.0,75.6,40164.000000,10200.000000,0
602922,25000.0,1,4,3,5,103000.0,1,2,5.27,0.0,5.0,0.0,92.4,17275.000000,18700.000000,0
602923,25000.0,1,4,0,4,55000.0,0,2,5.52,0.0,9.0,0.0,56.8,13860.000000,24400.000000,0
602924,26500.0,1,2,10,1,92000.0,2,2,29.60,1.0,10.0,0.0,65.1,115511.000000,118600.000000,0
602925,21000.0,0,1,10,1,65000.0,1,1,17.09,0.0,11.0,0.0,30.6,212337.000000,76300.000000,0
602926,8000.0,0,1,9,1,50000.0,1,2,17.62,0.0,11.0,0.0,63.2,211412.000000,7300.000000,0
602927,12000.0,0,2,4,5,40000.0,1,2,25.65,1.0,8.0,0.0,73.4,20671.000000,11900.000000,0
602928,7000.0,0,3,10,5,57000.0,2,2,16.80,2.0,13.0,2.0,27.1,32135.000000,9900.000000,0
602929,10000.0,0,1,1,5,75000.0,2,2,33.66,0.0,9.0,0.0,34.7,88120.000000,30300.000000,0
602930,13150.0,1,3,8,1,30000.0,2,6,1.00,0.0,3.0,0.0,3.2,158977.000000,20700.000000,0
602931,7500.0,0,2,8,5,40000.0,2,2,25.63,0.0,10.0,1.0,43.9,18611.000000,14500.000000,0
602932,12000.0,0,2,0,1,63000.0,2,1,23.69,1.0,13.0,0.0,69.7,237002.000000,30300.000000,0
602933,11575.0,0,4,10,5,25400.0,2,1,27.08,0.0,9.0,0.0,65.0,19798.000000,28100.000000,0
602934,10000.0,0,2,8,5,31000.0,2,2,28.69,0.0,9.0,1.0,82.1,25274.000000,17100.000000,0
602935,24000.0,0,2,10,1,79000.0,2,4,3.90,0.0,5.0,0.0,84.5,140285.000000,10200.000000,0
602936,13000.0,1,4,5,5,35000.0,2,2,30.90,0.0,9.0,1.0,61.3,34178.000000,18000.000000,0
602937,12000.0,1,5,1,5,64400.0,1,2,27.19,1.0,17.0,0.0,30.6,58418.000000,27000.000000,0
602938,20000.0,0,2,10,5,100000.0,2,1,10.83,0.0,8.0,1.0,79.8,33307.000000,41700.000000,0

In [206]:
df_c.loan_status.value_counts()

0    601081
1      1858
Name: loan_status, dtype: int64

In [207]:
601081/1858

323.5096878363832